/**
 * OpenSpec workflow skills for DeepSeek Harness.
 *
 * Registers the 12 OpenSpec workflow skills (the `openspec-*` SKILL.md set)
 * under their canonical kebab-case names — so `/openspec-new-change`
 * works natively through DSH's user-invocation injection and the `skill` tool —
 * plus the Claude-style `/opsx-<id>` command aliases (`/opsx:new` → `/opsx-new`)
 * as user-only skills that resolve to the canonical body.
 *
 * The skill bodies are generated by `scripts/sync-openspec-skills.mjs` from the
 * OpenSpec repository; see `src/skills.ts`.
 *
 * @module @dragon-talon/dsh-openspec
 */

import type { Context } from '@deepseek-ai/cordis'
import type { SkillSource } from '@deepseek-ai/dsh-skill'
import { OPENSPEC_SKILLS, OPSX_TO_SKILL } from './skills.ts'

/** Cordis plugin name. */
export const name = 'dsh-openspec'
/** Service required to register the workflow skills. */
export const inject = ['skills']

/** Runtime-source label for both the canonical skills and their command aliases. */
const SOURCE: SkillSource = 'runtime'

export interface Config {
  /**
   * Register the `/opsx-<id>` command aliases as user-only skills
   * (`modelInvocable: false`), keeping the model catalog to the 12 canonical
   * `openspec-*` names. Defaults to true.
   */
  aliases?: boolean
}

/**
 * Register the 12 canonical OpenSpec skills and (by default) their `/opsx-*`
 * command aliases on `ctx.skills`.
 * @param ctx - the composed host/preset context carrying `ctx.skills`.
 * @param config - `aliases` toggles the command-alias registrations.
 */
export function apply(ctx: Context, config: Config = {}): void {
  const byName = new Map(OPENSPEC_SKILLS.map((skill) => [skill.name, skill]))

  for (const skill of OPENSPEC_SKILLS) {
    ctx.skills.register({
      name: skill.name,
      description: skill.description,
      content: skill.content,
      source: SOURCE,
    })
  }

  if (config.aliases === false) return
  for (const [id, canonicalName] of Object.entries(OPSX_TO_SKILL)) {
    const canonical = byName.get(canonicalName)
    if (canonical === undefined) continue
    ctx.skills.register({
      name: `opsx-${id}`,
      description: canonical.description,
      content: canonical.content,
      source: SOURCE,
      // Command aliases answer only the human `/opsx-<id>` gesture; the model
      // catalog and `skill` tool surface the canonical names instead.
      invocation: { modelInvocable: false, userInvocable: true },
    })
  }
}
